from pathlib import Path

p=Path('tarifs-loc.html')
s=p.read_text(encoding='utf-8')

old="Avec une plateforme à commission, chaque réservation peut encore prélever une part de votre chiffre d’affaires."
new="Avec une plateforme à commission, chaque nouvelle réservation peut entraîner un nouveau prélèvement sur votre chiffre d’affaires."
if old in s:
    s=s.replace(old,new,1)

if 'id="locToolkit"' not in s:
    css_anchor='@media(max-width:700px){.formgrid,.paygrid,.steps{grid-template-columns:1fr}.hero{padding:22px}.offer{text-align:center}}'
    assert s.count(css_anchor)==1
    css='''.toolkit{border-color:#f6c45355;background:linear-gradient(145deg,#ffffff08,#2dd4bf08)}.toolkitLang{display:none}html[lang^="fr"] .toolkitLang[data-toolkit-lang="fr"],html[lang^="en"] .toolkitLang[data-toolkit-lang="en"],html[lang^="es"] .toolkitLang[data-toolkit-lang="es"],html[lang^="pt"] .toolkitLang[data-toolkit-lang="pt"],html[lang^="it"] .toolkitLang[data-toolkit-lang="it"],html[lang^="de"] .toolkitLang[data-toolkit-lang="de"],html[lang^="nl"] .toolkitLang[data-toolkit-lang="nl"],html[lang^="ar"] .toolkitLang[data-toolkit-lang="ar"]{display:block}.toolkitKicker{display:inline-flex;padding:6px 9px;border-radius:999px;border:1px solid #f6c45366;background:#f6c4530b;color:#fff0b8;font-size:10px;font-weight:1000;letter-spacing:.06em}.toolkitGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.toolCard{padding:14px;border-radius:18px;border:1px solid #ffffff1c;background:#03120d99}.toolCard .ico{font-size:24px}.toolCard strong{display:block;margin-top:8px;color:#fff3cf;font-size:14px}.toolCard span{display:block;margin-top:5px;color:#cfe0d8;font-size:11px;line-height:1.45;font-weight:800}.toolkitBottom{margin-top:13px;padding:12px;border-radius:16px;border:1px solid #22c55e55;background:#22c55e0c;color:#dcffea;font-weight:1000;text-align:center}@media(max-width:760px){.toolkitGrid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.toolkitGrid{grid-template-columns:1fr}}\n'''
    s=s.replace(css_anchor,css+css_anchor,1)

    anchor='<section class="box">\n<h2 id="tiersTitle">Paliers DIGIY LOC</h2>'
    assert s.count(anchor)==1
    section='''<section class="box toolkit" id="locToolkit" aria-label="Outils inclus dans DIGIY LOC">
<div class="toolkitLang" data-toolkit-lang="fr"><span class="toolkitKicker">CE QUE VOUS DÉBLOQUEZ APRÈS ADHÉSION</span><h2>Votre boîte à outils LOC, pas seulement une fiche.</h2><p>Vous disposez d’un espace de pilotage simple pour gérer votre logement, vos réservations et votre relation client sans dépendre d’une plateforme à commission.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>Espace sécurisé</strong><span>Accès PRO protégé par votre identifiant/PIN. Le client n’entre jamais dans votre espace de gestion.</span></div><div class="toolCard"><div class="ico">📅</div><strong>Planning & disponibilités</strong><span>Visualisez vos occupations et changez vos états Libre · Occupé · Fermé selon la réalité du terrain.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>Réservations</strong><span>Dates, logement, client, montant, état de la demande et suivi utile réunis dans votre espace.</span></div><div class="toolCard"><div class="ico">💬</div><strong>WhatsApp direct</strong><span>Les coordonnées et indications du client restent accessibles pour le contacter et confirmer directement.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>Vos tarifs</strong><span>Modifiez vos prix : nuit, semaine, mois, ménage et caution. Vous gardez la main sur votre grille.</span></div><div class="toolCard"><div class="ico">👥</div><strong>Répertoire clients</strong><span>Nom, téléphone, zone et notes professionnelles, avec appel ou WhatsApp direct.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>Photos du logement</strong><span>Gérez les visuels de votre hébergement et choisissez votre photo principale.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>QR du logement</strong><span>Votre QR ouvre la fiche publique du logement, jamais votre espace PRO sécurisé.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0 % commission DIGIYLYFE</strong><span>Le client vous contacte, vous décidez, vous encaissez directement. DIGIY reste l’outil, pas l’intermédiaire.</span></div></div><div class="toolkitBottom">Vous voyez l’outil avant de vous engager. Les commandes réelles s’ouvrent après validation de votre adhésion.</div></div>
<div class="toolkitLang" data-toolkit-lang="en"><span class="toolkitKicker">WHAT YOU UNLOCK AFTER JOINING</span><h2>Your LOC toolbox, not just a listing.</h2><p>A simple control space for your property, bookings and direct customer relationship.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>Secure member space</strong><span>Protected PRO access; customers never enter your management area.</span></div><div class="toolCard"><div class="ico">📅</div><strong>Calendar & availability</strong><span>Track occupancy and set Available · Occupied · Closed.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>Bookings</strong><span>Dates, guest, property, amount and request status in one place.</span></div><div class="toolCard"><div class="ico">💬</div><strong>Direct WhatsApp</strong><span>Contact and confirm directly with the customer.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>Your prices</strong><span>Edit nightly, weekly, monthly, cleaning and deposit amounts.</span></div><div class="toolCard"><div class="ico">👥</div><strong>Customer directory</strong><span>Name, phone, area and notes with direct call or WhatsApp.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>Property photos</strong><span>Manage visuals and select the main image.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>Property QR</strong><span>The QR opens the public listing, never the secure PRO space.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0% DIGIYLYFE commission</strong><span>You decide and collect directly.</span></div></div><div class="toolkitBottom">See the tool before you commit. Real controls unlock after membership validation.</div></div>
<div class="toolkitLang" data-toolkit-lang="es"><span class="toolkitKicker">LO QUE DESBLOQUEA TRAS LA ADHESIÓN</span><h2>Su caja de herramientas LOC, no solo una ficha.</h2><p>Gestione alojamiento, reservas y relación directa con el cliente.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>Espacio seguro</strong><span>Acceso PRO protegido.</span></div><div class="toolCard"><div class="ico">📅</div><strong>Calendario</strong><span>Libre · Ocupado · Cerrado.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>Reservas</strong><span>Fechas, cliente, importe y estado.</span></div><div class="toolCard"><div class="ico">💬</div><strong>WhatsApp directo</strong><span>Contacto y confirmación directa.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>Sus tarifas</strong><span>Noche, semana, mes, limpieza y fianza.</span></div><div class="toolCard"><div class="ico">👥</div><strong>Clientes</strong><span>Nombre, teléfono, zona y notas.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>Fotos</strong><span>Gestione imágenes y foto principal.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>QR</strong><span>Abre la ficha pública.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0 % comisión</strong><span>Relación y pago directos.</span></div></div><div class="toolkitBottom">Vea la herramienta antes de comprometerse. La gestión real se activa tras la adhesión.</div></div>
<div class="toolkitLang" data-toolkit-lang="pt"><span class="toolkitKicker">O QUE DESBLOQUEIA APÓS A ADESÃO</span><h2>A sua caixa de ferramentas LOC.</h2><p>Gestão simples do alojamento, reservas e relação direta.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>Espaço seguro</strong><span>Acesso PRO protegido.</span></div><div class="toolCard"><div class="ico">📅</div><strong>Calendário</strong><span>Livre · Ocupado · Fechado.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>Reservas</strong><span>Datas, cliente, valor e estado.</span></div><div class="toolCard"><div class="ico">💬</div><strong>WhatsApp direto</strong><span>Contacto e confirmação direta.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>Tarifas</strong><span>Noite, semana, mês, limpeza e caução.</span></div><div class="toolCard"><div class="ico">👥</div><strong>Clientes</strong><span>Nome, telefone, zona e notas.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>Fotos</strong><span>Gerir imagens e foto principal.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>QR</strong><span>Abre a ficha pública.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0 % comissão</strong><span>Relação e pagamento diretos.</span></div></div><div class="toolkitBottom">Veja a ferramenta antes de aderir. A gestão real é ativada após validação.</div></div>
<div class="toolkitLang" data-toolkit-lang="it"><span class="toolkitKicker">COSA SBLOCCHI DOPO L’ADESIONE</span><h2>La tua cassetta degli attrezzi LOC.</h2><p>Gestione semplice di struttura, prenotazioni e relazione diretta.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>Spazio sicuro</strong><span>Accesso PRO protetto.</span></div><div class="toolCard"><div class="ico">📅</div><strong>Calendario</strong><span>Libero · Occupato · Chiuso.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>Prenotazioni</strong><span>Date, cliente, importo e stato.</span></div><div class="toolCard"><div class="ico">💬</div><strong>WhatsApp diretto</strong><span>Contatto e conferma diretti.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>Tariffe</strong><span>Notte, settimana, mese, pulizia e cauzione.</span></div><div class="toolCard"><div class="ico">👥</div><strong>Clienti</strong><span>Nome, telefono, zona e note.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>Foto</strong><span>Gestione immagini e foto principale.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>QR</strong><span>Apre la scheda pubblica.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0 % commissioni</strong><span>Rapporto e pagamento diretti.</span></div></div><div class="toolkitBottom">Guarda lo strumento prima di aderire. I comandi reali si attivano dopo la convalida.</div></div>
<div class="toolkitLang" data-toolkit-lang="de"><span class="toolkitKicker">NACH DER MITGLIEDSCHAFT FREIGESCHALTET</span><h2>Ihre LOC-Werkzeuge.</h2><p>Einfache Verwaltung von Unterkunft, Buchungen und direktem Kundenkontakt.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>Sicherer Bereich</strong><span>Geschützter PRO-Zugang.</span></div><div class="toolCard"><div class="ico">📅</div><strong>Kalender</strong><span>Frei · Belegt · Geschlossen.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>Buchungen</strong><span>Daten, Gast, Betrag und Status.</span></div><div class="toolCard"><div class="ico">💬</div><strong>Direktes WhatsApp</strong><span>Direkter Kontakt und Bestätigung.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>Preise</strong><span>Nacht, Woche, Monat, Reinigung und Kaution.</span></div><div class="toolCard"><div class="ico">👥</div><strong>Kunden</strong><span>Name, Telefon, Gebiet und Notizen.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>Fotos</strong><span>Bilder und Hauptfoto verwalten.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>QR</strong><span>Öffnet die öffentliche Unterkunftsseite.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0 % Provision</strong><span>Direkte Beziehung und Zahlung.</span></div></div><div class="toolkitBottom">Sehen Sie das Werkzeug vor dem Beitritt. Die echte Verwaltung wird danach freigeschaltet.</div></div>
<div class="toolkitLang" data-toolkit-lang="nl"><span class="toolkitKicker">WAT U NA AANSLUITING KRIJGT</span><h2>Uw LOC-gereedschapskist.</h2><p>Eenvoudig beheer van accommodatie, boekingen en direct klantcontact.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>Beveiligde ruimte</strong><span>Beschermde PRO-toegang.</span></div><div class="toolCard"><div class="ico">📅</div><strong>Kalender</strong><span>Vrij · Bezet · Gesloten.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>Boekingen</strong><span>Data, klant, bedrag en status.</span></div><div class="toolCard"><div class="ico">💬</div><strong>Direct WhatsApp</strong><span>Direct contact en bevestiging.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>Tarieven</strong><span>Nacht, week, maand, schoonmaak en borg.</span></div><div class="toolCard"><div class="ico">👥</div><strong>Klanten</strong><span>Naam, telefoon, regio en notities.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>Foto’s</strong><span>Beheer beelden en hoofdfoto.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>QR</strong><span>Opent de openbare accommodatiepagina.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0% commissie</strong><span>Directe relatie en betaling.</span></div></div><div class="toolkitBottom">Bekijk de tool vóór aansluiting. Echte bediening wordt daarna geactiveerd.</div></div>
<div class="toolkitLang" data-toolkit-lang="ar"><span class="toolkitKicker">ما الذي تحصل عليه بعد الاشتراك</span><h2>أدوات DIGIY LOC الخاصة بك.</h2><p>إدارة بسيطة للسكن والحجوزات والعلاقة المباشرة مع العميل.</p><div class="toolkitGrid"><div class="toolCard"><div class="ico">🔐</div><strong>مساحة آمنة</strong><span>دخول مهني محمي.</span></div><div class="toolCard"><div class="ico">📅</div><strong>التقويم</strong><span>متاح · مشغول · مغلق.</span></div><div class="toolCard"><div class="ico">🧾</div><strong>الحجوزات</strong><span>التواريخ والعميل والمبلغ والحالة.</span></div><div class="toolCard"><div class="ico">💬</div><strong>واتساب مباشر</strong><span>تواصل وتأكيد مباشر.</span></div><div class="toolCard"><div class="ico">🏷️</div><strong>الأسعار</strong><span>ليلة، أسبوع، شهر، تنظيف وتأمين.</span></div><div class="toolCard"><div class="ico">👥</div><strong>العملاء</strong><span>الاسم والهاتف والمنطقة والملاحظات.</span></div><div class="toolCard"><div class="ico">🖼️</div><strong>الصور</strong><span>إدارة الصور واختيار الصورة الرئيسية.</span></div><div class="toolCard"><div class="ico">🔳</div><strong>QR</strong><span>يفتح صفحة السكن العامة.</span></div><div class="toolCard"><div class="ico">🤝</div><strong>0٪ عمولة</strong><span>علاقة ودفع مباشران.</span></div></div><div class="toolkitBottom">شاهد الأداة قبل الاشتراك. يتم تفعيل الإدارة الفعلية بعد اعتماد العضوية.</div></div>
</section>\n\n'''
    s=s.replace(anchor,section+anchor,1)

assert 'id="locToolkit"' in s
assert new in s
p.write_text(s,encoding='utf-8')
