from pathlib import Path
import re

ROOT=Path('.')

def rep(text, old, new, label, count=1):
    n=text.count(old)
    if n < count:
        raise SystemExit(f'{label}: expected at least {count}, found {n}')
    return text.replace(old,new,count)

# 1) Bordeaux direct showcase -------------------------------------------------
p=ROOT/'bordeaux.html'
s=p.read_text(encoding='utf-8')
s=rep(s,'bordeaux-urbain-v1-8quartiers-27exemples-8langues-20260826','bordeaux-urbain-v2-i18n-partagee-8langues-20260827','bordeaux build')
s=rep(s,'</main>\n<script>\n(function(){\'use strict\';','</main>\n<script src="/assets/digiy-bordeaux-i18n-v1.js?v=20260827-bordeaux-i18n-v1"></script>\n<script>\n(function(){\'use strict\';','bordeaux shared data loader')
s=rep(s,"function t(){return COPY[currentLang()]||COPY.fr;}","function t(){return COPY[currentLang()]||COPY.fr;}\nfunction pack(){var d=window.DIGIY_BORDEAUX_DATA||{},l=currentLang();return d[l]||d.fr||null;}",'bordeaux pack helper')
s=rep(s,"function renderNeeds(){var el=document.getElementById('needs');el.innerHTML='';NEEDS.forEach(function(n){var b=document.createElement('button');b.className='need'+(state.need===n[0]?' on':'');b.innerHTML='<strong>'+n[1]+'</strong><span>'+n[2]+'</span>';b.onclick=function(){state.need=state.need===n[0]?'':n[0];syncUrl();};el.appendChild(b);});}","function renderNeeds(){var el=document.getElementById('needs');el.innerHTML='';var pk=pack(),labels=pk&&pk.needs?pk.needs:{};NEEDS.forEach(function(n){var b=document.createElement('button');b.className='need'+(state.need===n[0]?' on':'');b.innerHTML='<strong>'+n[1]+'</strong><span>'+(labels[n[0]]||n[2])+'</span>';b.onclick=function(){state.need=state.need===n[0]?'':n[0];syncUrl();};el.appendChild(b);});}",'bordeaux needs renderer')
old_cards="function renderCards(){var el=document.getElementById('cards');el.innerHTML='';var keys=state.need?[state.need]:NEEDS.map(function(n){return n[0]});keys.forEach(function(k){(EX[k]||[]).forEach(function(row,i){var effective=state.local||row[1];var a=document.createElement('article');a.className='card'+(k==='guidance'?' voiceCard':'');var services=row[2].map(function(s){return '<span class=\"chip\">'+s+'</span>';}).join('');var u=new URL('/demo-bordeaux.html',location.origin);u.searchParams.set('need',k);u.searchParams.set('variant',String(i+1));u.searchParams.set('local',effective);u.searchParams.set('lang',currentLang());a.innerHTML='<div class=\"badge\">'+t().badge+'</div><h3>'+row[0]+'</h3><div class=\"meta\">📍 '+zoneLabel(effective)+' · BORDEAUX</div><div class=\"chips\">'+services+'<span class=\"chip\">45 € / mois</span><span class=\"chip\">0 % commission</span></div><a class=\"btn '+(k==='guidance'?'secondary':'primary')+'\" href=\"'+u.pathname+u.search+'\">'+(k==='guidance'?t().voice:t().demo)+'</a>';el.appendChild(a);});});}"
new_cards="function renderCards(){var el=document.getElementById('cards');el.innerHTML='';var pk=pack(),ex=pk&&pk.ex?pk.ex:EX,ui=pk&&pk.ui?pk.ui:null;var keys=state.need?[state.need]:NEEDS.map(function(n){return n[0]});keys.forEach(function(k){(ex[k]||[]).forEach(function(row,i){var effective=state.local||row[1];var a=document.createElement('article');a.className='card'+(k==='guidance'?' voiceCard':'');var services=row[2].map(function(s){return '<span class=\"chip\">'+s+'</span>';}).join('');var u=new URL('/demo-bordeaux.html',location.origin);u.searchParams.set('need',k);u.searchParams.set('variant',String(i+1));u.searchParams.set('local',effective);u.searchParams.set('lang',currentLang());var city=ui&&ui.city?ui.city:'BORDEAUX',price=ui&&ui.price?ui.price:'45 € / mois',commission=ui&&ui.commission?ui.commission:'0 % commission';a.innerHTML='<div class=\"badge\">'+t().badge+'</div><h3>'+row[0]+'</h3><div class=\"meta\">📍 '+zoneLabel(effective)+' · '+city+'</div><div class=\"chips\">'+services+'<span class=\"chip\">'+price+'</span><span class=\"chip\">'+commission+'</span></div><a class=\"btn '+(k==='guidance'?'secondary':'primary')+'\" href=\"'+u.pathname+u.search+'\">'+(k==='guidance'?t().voice:t().demo)+'</a>';el.appendChild(a);});});}"
s=rep(s,old_cards,new_cards,'bordeaux cards renderer')
# Remove remaining French LA VOIX wording in translated shell copy.
s=s.replace("needLead:'9 portas simples. LA VOIX é um motor de pesquisa, nunca uma profissão.'","needLead:'9 portas simples. A VOZ é um motor de pesquisa, nunca uma profissão.'")
s=s.replace("needLead:'9 porte semplici. LA VOIX resta un motore di ricerca, mai un mestiere.'","needLead:'9 porte semplici. LA VOCE resta un motore di ricerca, mai un mestiere.'")
s=s.replace("needLead:'9 einfache Türen. LA VOIX bleibt eine Suchmaschine, niemals ein Beruf.'","needLead:'9 einfache Türen. DIE STIMME bleibt eine Suchmaschine, niemals ein Beruf.'")
s=s.replace("needLead:'9 eenvoudige ingangen. LA VOIX blijft een zoekmachine, nooit een beroep.'","needLead:'9 eenvoudige ingangen. DE STEM blijft een zoekmachine, nooit een beroep.'")
s=s.replace("needLead:'9 puertas simples. LA VOIX es un motor de búsqueda, no un oficio.'","needLead:'9 puertas simples. LA VOZ es un motor de búsqueda, no un oficio.'")
s=s.replace("needLead:'9 simple doors. LA VOIX is a search engine, never a trade.'","needLead:'9 simple doors. THE VOICE is a search engine, never a trade.'")
s=s.replace("needLead:'9 أبواب بسيطة. LA VOIX محرك بحث وليست مهنة.'","needLead:'9 أبواب بسيطة. الصوت محرك بحث وليس مهنة.'")
p.write_text(s,encoding='utf-8')

# 2) Territory projection -----------------------------------------------------
p=ROOT/'assets/digiy-territoire-bordeaux-projection-v1.js'
s=p.read_text(encoding='utf-8')
s=rep(s,'/* DIGIYLYFE — projection commerciale Bordeaux V1','/* DIGIYLYFE — projection commerciale Bordeaux V2 · i18n partagée','projection version')
s=rep(s,"function lang(){var l=(document.documentElement.lang||'fr').slice(0,2).toLowerCase();return C[l]?l:'fr'}\n  function t(){return C[lang()]||C.fr}","function lang(){var q=(p().get('lang')||'').slice(0,2).toLowerCase(),d=(document.documentElement.lang||'fr').slice(0,2).toLowerCase(),l=C[q]?q:d;return C[l]?l:'fr'}\n  function t(){return C[lang()]||C.fr}\n  function pack(){var d=window.DIGIY_BORDEAUX_DATA||{},l=lang();return d[l]||d.fr||null}",'projection pack helper')
old_card="function card(k,row,i){var local=p().get('local')||row[1];if(local==='all')local=row[1];var a=document.createElement('article');a.className='card';a.setAttribute('data-bordeaux-placeholder',k+'-'+i);a.style.cssText='border-style:dashed;border-color:rgba(214,179,106,.68);background:linear-gradient(145deg,rgba(122,41,65,.34),rgba(214,179,106,.09))';var u=new URL('/demo-bordeaux.html',location.origin);u.searchParams.set('need',k);u.searchParams.set('variant',String(i+1));u.searchParams.set('local',local);u.searchParams.set('lang',lang());var badge=document.createElement('div');badge.textContent=t().badge;badge.style.cssText='display:inline-flex;margin-bottom:10px;padding:5px 8px;border-radius:999px;border:1px solid rgba(214,179,106,.55);color:#fff0c8;font-size:9px;font-weight:1000';var h=document.createElement('h3');h.textContent=row[0];var sum=document.createElement('p');sum.className='summary';sum.textContent=k==='guidance'?'LA VOIX permet de dire ce que l’on cherche au lieu de parcourir les catégories.':t().summary;var meta=document.createElement('div');meta.className='meta';meta.textContent='📍 '+(Z[local]||'Bordeaux')+' · BORDEAUX\\n🪪 '+t().meta;meta.style.whiteSpace='pre-line';var sv=document.createElement('div');sv.className='services';row[2].concat(k==='guidance'?['Recherche vocale','Pas une fiche métier']:['Carte digitale · QR','45 € / mois','0 % commission']).forEach(function(x){var sp=document.createElement('span');sp.className='service';sp.textContent=x;sv.appendChild(sp)});var ac=document.createElement('div');ac.className='actions';var link=document.createElement('a');link.href=u.pathname+u.search;link.textContent=k==='guidance'?t().voice:t().demo;ac.appendChild(link);a.append(badge,h,sum,meta,sv,ac);return a}"
new_card="function card(k,row,i){var local=p().get('local')||row[1];if(local==='all')local=row[1];var pk=pack(),ui=pk&&pk.ui?pk.ui:null;var a=document.createElement('article');a.className='card';a.setAttribute('data-bordeaux-placeholder',k+'-'+i);a.style.cssText='border-style:dashed;border-color:rgba(214,179,106,.68);background:linear-gradient(145deg,rgba(122,41,65,.34),rgba(214,179,106,.09))';var u=new URL('/demo-bordeaux.html',location.origin);u.searchParams.set('need',k);u.searchParams.set('variant',String(i+1));u.searchParams.set('local',local);u.searchParams.set('lang',lang());var badge=document.createElement('div');badge.textContent=t().badge;badge.style.cssText='display:inline-flex;margin-bottom:10px;padding:5px 8px;border-radius:999px;border:1px solid rgba(214,179,106,.55);color:#fff0c8;font-size:9px;font-weight:1000';var h=document.createElement('h3');h.textContent=row[0];var sum=document.createElement('p');sum.className='summary';sum.textContent=k==='guidance'?(ui&&ui.voiceSummary?ui.voiceSummary:'LA VOIX permet de dire ce que l’on cherche.'):(ui&&ui.summary?ui.summary:t().summary);var meta=document.createElement('div');meta.className='meta';meta.textContent='📍 '+(Z[local]||'Bordeaux')+' · '+(ui&&ui.city?ui.city:'BORDEAUX')+'\\n🪪 '+t().meta;meta.style.whiteSpace='pre-line';var sv=document.createElement('div');sv.className='services';var extra=k==='guidance'?[ui&&ui.voiceChip?ui.voiceChip:'Recherche vocale',ui&&ui.notTrade?ui.notTrade:'Pas une fiche métier']:[ui&&ui.card?ui.card:'Carte digitale · QR',ui&&ui.price?ui.price:'45 € / mois',ui&&ui.commission?ui.commission:'0 % commission'];row[2].concat(extra).forEach(function(x){var sp=document.createElement('span');sp.className='service';sp.textContent=x;sv.appendChild(sp)});var ac=document.createElement('div');ac.className='actions';var link=document.createElement('a');link.href=u.pathname+u.search;link.textContent=k==='guidance'?t().voice:t().demo;ac.appendChild(link);a.append(badge,h,sum,meta,sv,ac);return a}"
s=rep(s,old_card,new_card,'projection card')
old_render="function render(){if(!active()||busy)return;var r=document.getElementById('results');if(!r)return;busy=true;clear(r);var need=p().get('need')||'',real=Array.prototype.slice.call(r.querySelectorAll('.card:not([data-bordeaux-placeholder])')),empty=r.querySelector('.empty');if(empty)empty.remove();var keys=need?[need]:ORDER.slice(),limit=3;if(need)limit=Math.max(0,3-real.length);var total=need?Math.min(limit,(EX[need]||[]).length):27;if(!real.length){var status=document.getElementById('status');if(status)status.textContent=t().empty}if(total>0){r.appendChild(title(total,!!need));keys.forEach(function(k){(EX[k]||[]).slice(0,need?limit:3).forEach(function(row,i){r.appendChild(card(k,row,i))})})}busy=false}"
new_render="function render(){if(!active()||busy)return;var r=document.getElementById('results');if(!r)return;busy=true;clear(r);var need=p().get('need')||'',real=Array.prototype.slice.call(r.querySelectorAll('.card:not([data-bordeaux-placeholder])')),empty=r.querySelector('.empty'),pk=pack(),ex=pk&&pk.ex?pk.ex:EX;if(empty)empty.remove();var keys=need?[need]:ORDER.slice(),limit=3;if(need)limit=Math.max(0,3-real.length);var total=need?Math.min(limit,(ex[need]||[]).length):27;if(!real.length){var status=document.getElementById('status');if(status)status.textContent=t().empty}if(total>0){r.appendChild(title(total,!!need));keys.forEach(function(k){(ex[k]||[]).slice(0,need?limit:3).forEach(function(row,i){r.appendChild(card(k,row,i))})})}busy=false}"
s=rep(s,old_render,new_render,'projection render')
p.write_text(s,encoding='utf-8')

# 3) Territory loader/cache ---------------------------------------------------
p=ROOT/'territoire.html'
s=p.read_text(encoding='utf-8')
old='<script src="/assets/digiy-territoire-bordeaux-projection-v1.js?v=20260827-bordeaux-master-v1" defer></script>'
new='<script src="/assets/digiy-bordeaux-i18n-v1.js?v=20260827-bordeaux-i18n-v1" defer></script>\n<script src="/assets/digiy-territoire-bordeaux-projection-v1.js?v=20260827-bordeaux-i18n-v2" defer></script>'
s=rep(s,old,new,'territory bordeaux loader')
p.write_text(s,encoding='utf-8')

# 4) Demo --------------------------------------------------------------------
p=ROOT/'demo-bordeaux.html'
s=p.read_text(encoding='utf-8')
s=rep(s,'</main>\n<script>\n(function(){\'use strict\';','</main>\n<script src="/assets/digiy-bordeaux-i18n-v1.js?v=20260827-bordeaux-i18n-v1"></script>\n<script>\n(function(){\'use strict\';','demo shared data loader')
s=rep(s,'<div class="shot" id="g1">📍<span>APERÇU PRINCIPAL</span></div><div class="shot" id="g2">📲<span>CONTACT DIRECT</span></div><div class="shot" id="g3">🪪<span>CARTE DIGITALE</span></div>','<div class="shot" id="g1">📍<span id="g1Label">APERÇU PRINCIPAL</span></div><div class="shot" id="g2">📲<span id="g2Label">CONTACT DIRECT</span></div><div class="shot" id="g3">🪪<span id="g3Label">CARTE DIGITALE</span></div>','demo gallery labels')
s=rep(s,'<div class="chips"><span class="chip">QR</span><span class="chip">Contact direct</span><span class="chip">0 % commission</span><span class="chip">Identité propriétaire</span></div>','<div class="chips"><span class="chip">QR</span><span class="chip" id="promiseDirect">Contact direct</span><span class="chip" id="promiseCommission">0 % commission</span><span class="chip" id="promiseOwner">Identité propriétaire</span></div>','demo promise chips')
needle="document.querySelectorAll('[data-l]').forEach(function(b){b.classList.toggle('on',b.dataset.l===l)});}"
s=rep(s,needle,"document.querySelectorAll('[data-l]').forEach(function(b){b.classList.toggle('on',b.dataset.l===l)});renderShared(l);}",'demo lang render hook')
insert_marker="document.querySelectorAll('[data-l]').forEach(function(b){b.onclick=function(){langSet(b.dataset.l)}});"
render_shared="""function renderShared(l){var packs=window.DIGIY_BORDEAUX_DATA||{},pk=packs[l]||packs.fr;if(!pk)return;var ex=pk.ex||D,rr=(ex[need]||ex.transport||D.transport)[variant-1]||(ex.transport||D.transport)[0],ui2=pk.ui||{},zone2=local&&Z[local]?Z[local]:(Z[rr[1]]||'Bordeaux');row=rr;document.getElementById('title').textContent=row[0];document.getElementById('zone').textContent='📍 '+zone2+' · '+(ui2.city||'BORDEAUX');document.getElementById('services').innerHTML='';row[2].forEach(function(x){var sp=document.createElement('span');sp.className='chip';sp.textContent=x;document.getElementById('services').appendChild(sp)});document.getElementById('g1').firstChild.nodeValue=row[3];document.getElementById('g2').firstChild.nodeValue=row[4];document.getElementById('g3').firstChild.nodeValue=row[5];document.getElementById('g1Label').textContent=ui2.galleryMain||'APERÇU PRINCIPAL';document.getElementById('g2Label').textContent=ui2.galleryContact||'CONTACT DIRECT';document.getElementById('g3Label').textContent=ui2.galleryCard||'CARTE DIGITALE';document.getElementById('promiseDirect').textContent=ui2.promiseDirect||'Contact direct';document.getElementById('promiseCommission').textContent=ui2.commission||'0 % commission';document.getElementById('promiseOwner').textContent=ui2.promiseOwner||'Identité propriétaire';document.getElementById('voiceBadge').textContent=ui2.voiceBadge||'LA VOIX · RECHERCHE VOCALE';if(need==='guidance'){var ve=document.getElementById('voiceExamples');ve.innerHTML='';row[2].forEach(function(x){var d=document.createElement('div');d.className='voiceQ';d.textContent=x;ve.appendChild(d)})}var ju=new URL('/adhesion-bordeaux.html',location.origin);ju.searchParams.set('need',need);ju.searchParams.set('local',local||row[1]);ju.searchParams.set('lang',l);document.getElementById('join').href=ju.pathname+ju.search;var bu=new URL('/bordeaux.html',location.origin);bu.searchParams.set('need',need);if(local)bu.searchParams.set('local',local);bu.searchParams.set('lang',l);['back','return'].forEach(function(id){document.getElementById(id).href=bu.pathname+bu.search});var vb=document.querySelector('#voicePanel .secondary');if(vb)vb.href=bu.pathname+bu.search;}\n"""
s=rep(s,insert_marker,render_shared+insert_marker,'demo shared renderer insert')
p.write_text(s,encoding='utf-8')

# 5) Membership context -------------------------------------------------------
p=ROOT/'adhesion-bordeaux.html'
s=p.read_text(encoding='utf-8')
s=rep(s,'</main>\n<script>\n(function(){\'use strict\';','</main>\n<script src="/assets/digiy-bordeaux-i18n-v1.js?v=20260827-bordeaux-i18n-v1"></script>\n<script>\n(function(){\'use strict\';','adhesion shared data loader')
s=rep(s,"var m=MAP[need]||['🪪','PROFESSIONNEL'];var L={","var m=MAP[need]||['🪪','PROFESSIONNEL'];var PRO={fr:'PROFESSIONNEL',en:'PROFESSIONAL',es:'PROFESIONAL',pt:'PROFISSIONAL',it:'PROFESSIONISTA',de:'PROFI',nl:'PROFESSIONAL',ar:'مهني'};var L={",'adhesion professional labels')
old="document.querySelectorAll('[data-l]').forEach(function(b){b.classList.toggle('on',b.dataset.l===l)});var u=new URL('/preparer-ma-carte.html',location.origin);"
new="document.querySelectorAll('[data-l]').forEach(function(b){b.classList.toggle('on',b.dataset.l===l)});var packs=window.DIGIY_BORDEAUX_DATA||{},pk=packs[l]||packs.fr||null,labels=pk&&pk.needs?pk.needs:{},zones=window.DIGIY_BORDEAUX_ZONES||{},ui2=pk&&pk.ui?pk.ui:{},label=need?(labels[need]||m[1]):(PRO[l]||PRO.fr),where=local?(zones[local]||local.replace(/-/g,' ')):(ui2.city||'BORDEAUX');document.getElementById('context').textContent=m[0]+' '+label+' · '+where;var u=new URL('/preparer-ma-carte.html',location.origin);"
s=rep(s,old,new,'adhesion translated context')
s=rep(s,"}document.getElementById('context').textContent=m[0]+' '+m[1]+(local?' · '+local.replace(/-/g,' '):' · BORDEAUX');document.querySelectorAll('[data-l]')","}document.querySelectorAll('[data-l]')",'remove static french context')
p.write_text(s,encoding='utf-8')

# Guards ---------------------------------------------------------------------
checks={
 'bordeaux.html':['digiy-bordeaux-i18n-v1.js','function pack()','labels[n[0]]','pk&&pk.ex?pk.ex:EX','bordeaux-urbain-v2-i18n-partagee-8langues-20260827'],
 'assets/digiy-territoire-bordeaux-projection-v1.js':['projection commerciale Bordeaux V2','function pack()','pk&&pk.ex?pk.ex:EX','ui&&ui.voiceChip'],
 'territoire.html':['digiy-bordeaux-i18n-v1.js?v=20260827-bordeaux-i18n-v1','digiy-territoire-bordeaux-projection-v1.js?v=20260827-bordeaux-i18n-v2'],
 'demo-bordeaux.html':['digiy-bordeaux-i18n-v1.js','renderShared(l)','promiseCommission','ui2.galleryMain'],
 'adhesion-bordeaux.html':['digiy-bordeaux-i18n-v1.js','var PRO=','labels[need]','DIGIY_BORDEAUX_ZONES']
}
for f,markers in checks.items():
    text=(ROOT/f).read_text(encoding='utf-8')
    for marker in markers:
        if marker not in text:
            raise SystemExit(f'Missing guard {marker} in {f}')
print('Bordeaux i18n guards OK')
