from pathlib import Path

p = Path('sarlat.html')
s = p.read_text(encoding='utf-8')

repls = [
    ('<title>DIGIY SARLAT — Vallée de la Dordogne | DIGIYLYFE</title>', '<title>DIGIY VALLÉE DE LA DORDOGNE — Sarlat zone pilote | DIGIYLYFE</title>'),
    ('<meta name="description" content="DIGIY SARLAT : professionnels réels et places à prendre dans la Vallée de la Dordogne. Contact direct, 0 % commission, adhésion 45 € par mois.">', '<meta name="description" content="DIGIY Vallée de la Dordogne : Sarlat zone pilote, professionnels réels et places à prendre sur le territoire. Contact direct, 0 % commission, adhésion 45 € par mois.">'),
    ('<meta name="digiy-build" content="sarlat-dordogne-annonces-chaudes-v2-20260826">', '<meta name="digiy-build" content="dordogne-master-territoire-sarlat-pilote-v3-20260827">'),
    ('<h1>SARLAT<em>en direct</em></h1>', '<h1>DORDOGNE<em id="pilotLabel">Sarlat · zone pilote</em></h1>'),
    ('id="joinBtn">JE SUIS PROFESSIONNEL À SARLAT →', 'id="joinBtn">JE SUIS PROFESSIONNEL DANS LA VALLÉE →'),
    ('id="realTitle">Déjà ouverts à Sarlat</h2>', 'id="realTitle">Déjà ouverts · Sarlat zone pilote</h2>'),
    ('id="finalBtn" style="margin-top:14px">PRENDRE MA PLACE À SARLAT · 45 € / MOIS →', 'id="finalBtn" style="margin-top:14px">PRENDRE MA PLACE DANS LA VALLÉE · 45 € / MOIS →'),
    ('id="note">DIGIY SARLAT · pierre blonde · forêt du Périgord · rivière Dordogne · or DIGIYLYFE.', 'id="note">DIGIY VALLÉE DE LA DORDOGNE · Sarlat zone pilote · Périgord · rivière Dordogne · or DIGIYLYFE.'),
    ("var NEEDS=[['announcements','⚡','ANNONCES / SERVICES'],['transport','🚗','DRIVER'],['artisan','🔧','ARTISAN'],['accommodation','🏠','LOGEMENT / LOC'],['food','🍽️','RESTAURANT'],['shopping','🛍️','MON COMMERCE'],['beauty','💅','BEAUTÉ & BIEN-ÊTRE'],['jobs','💼','JOBS / MISSIONS'],['guidance','🎙️','LA VOIX']];", "var NEEDS=[['announcements','⚡','ANNONCES'],['transport','🚗','SE DÉPLACER'],['artisan','🔧','TROUVER UN ARTISAN'],['accommodation','🏠','DORMIR OU LOUER'],['food','🍽️','MANGER OU RÉSERVER'],['shopping','🛍️','ACHETER LOCAL'],['beauty','💅','BEAUTÉ & BIEN-ÊTRE'],['jobs','💼','EMPLOI ET MISSIONS'],['guidance','🎙️','LA VOIX']];"),
    ("['🚗 Chauffeur gare / Sarlat',['Gare de Sarlat','Transfert local','Réservation directe']]", "['🚗 Chauffeur gare / Vallée de la Dordogne',['Arrivée / départ','Transfert local','Réservation directe']]"),
    ("['🏠 Chambre de caractère',['Séjour Sarlat','Réservation directe','Équipements']]", "['🏠 Chambre de caractère',['Séjour Dordogne','Réservation directe','Équipements']]"),
    ("['🎙️ Trouver où manger',['« Où manger ce soir à Sarlat ? »','Recherche vocale','Résultat territorial']]", "['🎙️ Trouver où manger',['« Où manger ce soir dans la Vallée ? »','Recherche vocale','Résultat territorial']]"),
    ("['🎙️ Trouver où dormir',['« Je cherche une chambre à Sarlat »','Recherche vocale','Résultat territorial']]", "['🎙️ Trouver où dormir',['« Je cherche une chambre en Dordogne »','Recherche vocale','Résultat territorial']]"),
    ("['🎙️ Trouver un artisan',['« Je cherche un plombier à Sarlat »','Recherche vocale','Résultat territorial']]", "['🎙️ Trouver un artisan',['« Je cherche un artisan dans le secteur »','Recherche vocale','Résultat territorial']]"),
    ("<div class=\"meta\">📍 Sarlat-la-Canéda · Périgord Noir</div>", "<div class=\"meta\">📍 Vallée de la Dordogne · Périgord</div>"),
]

for old, new in repls:
    count = s.count(old)
    if count != 1:
        raise SystemExit(f'Guard failed ({count}) for: {old[:90]}')
    s = s.replace(old, new, 1)

old_copy_start = "var COPY={fr:"
copy_pos = s.find(old_copy_start)
state_pos = s.find(";var state={need:''}", copy_pos)
if copy_pos < 0 or state_pos < 0:
    raise SystemExit('COPY guard failed')

copy = r'''var COPY={
fr:{pilot:'Sarlat · zone pilote',ey:'PÉRIGORD NOIR · VALLÉE DE LA DORDOGNE · TERRITOIRE SAISONNIER',hero:'Les professionnels réels restent devant. Sarlat est la zone pilote ; les places à prendre projettent toute la Vallée de la Dordogne.',hot:'⚡ ANNONCES / BESOINS DU MOMENT →',real:'VOIR LES PROFESSIONNELS RÉELS →',join:'JE SUIS PROFESSIONNEL DANS LA VALLÉE →',price:'Identité locale · contact direct · 0 % commission',realTitle:'Déjà ouverts · Sarlat zone pilote',realLead:'Ici, ce sont de vraies présences DIGIYLYFE basées à Sarlat. Elles passent toujours devant les exemples.',open:'OUVRIR LA PRÉSENCE →',needTitle:'Que recherchez-vous ?',needLead:'ANNONCES remonte en premier. Puis les besoins humains du territoire. LA VOIX reste un moteur de recherche.',placesTitle:'Places à prendre dans la Vallée',placesLead:'Le vide ne s’affiche pas. Il se projette. Les exemples représentent des places ouvertes sur la Vallée de la Dordogne sans inventer de faux adhérents.',badge:'EXEMPLE · PLACE À PRENDRE',demo:'OUVRIR LE MODÈLE →',voice:'ESSAYER LA VOIX →',finalTitle:'Votre activité peut devenir la prochaine présence réelle du territoire.',finalLead:'Sarlat est la zone pilote. À mesure que de vrais professionnels arrivent, leurs vitrines prennent le relais devant les exemples.',finalBtn:'PRENDRE MA PLACE DANS LA VALLÉE · 45 € / MOIS →',note:'DIGIY VALLÉE DE LA DORDOGNE · Sarlat zone pilote · Périgord · rivière Dordogne · or DIGIYLYFE.',back:'← DIGIYLYFE FRANCE'},
en:{pilot:'Sarlat · pilot area',ey:'PÉRIGORD NOIR · DORDOGNE VALLEY · SEASONAL TERRITORY',hero:'Real professionals stay first. Sarlat is the pilot area; open places project the whole Dordogne Valley.',hot:'⚡ LISTINGS / CURRENT NEEDS →',real:'VIEW REAL PROFESSIONALS →',join:'I AM A PROFESSIONAL IN THE VALLEY →',price:'Local identity · direct contact · 0% commission',realTitle:'Already open · Sarlat pilot area',realLead:'These are real DIGIYLYFE presences based in Sarlat. They always appear before examples.',open:'OPEN PRESENCE →',needTitle:'What are you looking for?',needLead:'LISTINGS comes first, followed by human needs across the territory. THE VOICE remains a search engine.',placesTitle:'Open places in the Valley',placesLead:'Empty space is not shown. It is projected. Examples represent open places across the Dordogne Valley without inventing fake members.',badge:'EXAMPLE · PLACE AVAILABLE',demo:'OPEN MODEL →',voice:'TRY VOICE SEARCH →',finalTitle:'Your activity can become the next real presence in the territory.',finalLead:'Sarlat is the pilot area. As real professionals join, their own showcases take over before examples.',finalBtn:'TAKE MY PLACE IN THE VALLEY · €45 / MONTH →',note:'DIGIY DORDOGNE VALLEY · Sarlat pilot area · Périgord · Dordogne river · DIGIYLYFE gold.',back:'← DIGIYLYFE FRANCE'},
es:{pilot:'Sarlat · zona piloto',ey:'PÉRIGORD NOIR · VALLE DEL DORDOÑA · TERRITORIO ESTACIONAL',hero:'Los profesionales reales aparecen primero. Sarlat es la zona piloto; las plazas disponibles proyectan todo el Valle del Dordoña.',hot:'⚡ ANUNCIOS / NECESIDADES DEL MOMENTO →',real:'VER PROFESIONALES REALES →',join:'SOY PROFESIONAL EN EL VALLE →',price:'Identidad local · contacto directo · 0 % comisión',realTitle:'Ya abiertos · Sarlat zona piloto',realLead:'Estas son presencias DIGIYLYFE reales con base en Sarlat. Siempre aparecen antes de los ejemplos.',open:'ABRIR PRESENCIA →',needTitle:'¿Qué busca?',needLead:'ANUNCIOS aparece primero, seguido de las necesidades humanas del territorio. LA VOZ sigue siendo un buscador.',placesTitle:'Plazas disponibles en el Valle',placesLead:'El vacío no se muestra. Se proyecta. Los ejemplos representan plazas abiertas en el Valle del Dordoña sin inventar miembros falsos.',badge:'EJEMPLO · PLAZA DISPONIBLE',demo:'ABRIR MODELO →',voice:'PROBAR LA VOZ →',finalTitle:'Su actividad puede convertirse en la próxima presencia real del territorio.',finalLead:'Sarlat es la zona piloto. A medida que llegan profesionales reales, sus vitrinas sustituyen a los ejemplos.',finalBtn:'OCUPAR MI PLAZA EN EL VALLE · 45 € / MES →',note:'DIGIY VALLE DEL DORDOÑA · Sarlat zona piloto · Périgord · río Dordoña · oro DIGIYLYFE.',back:'← DIGIYLYFE FRANCIA'},
pt:{pilot:'Sarlat · zona piloto',ey:'PÉRIGORD NOIR · VALE DA DORDOGNE · TERRITÓRIO SAZONAL',hero:'Os profissionais reais aparecem primeiro. Sarlat é a zona piloto; os lugares disponíveis projetam todo o Vale da Dordogne.',hot:'⚡ ANÚNCIOS / NECESSIDADES DO MOMENTO →',real:'VER PROFISSIONAIS REAIS →',join:'SOU PROFISSIONAL NO VALE →',price:'Identidade local · contacto direto · 0 % comissão',realTitle:'Já abertos · Sarlat zona piloto',realLead:'Estas são presenças DIGIYLYFE reais sediadas em Sarlat. Aparecem sempre antes dos exemplos.',open:'ABRIR PRESENÇA →',needTitle:'O que procura?',needLead:'ANÚNCIOS vem primeiro, seguido das necessidades humanas do território. A VOZ continua a ser um motor de pesquisa.',placesTitle:'Lugares disponíveis no Vale',placesLead:'O vazio não é mostrado. É projetado. Os exemplos representam lugares abertos no Vale da Dordogne sem inventar membros falsos.',badge:'EXEMPLO · LUGAR DISPONÍVEL',demo:'ABRIR MODELO →',voice:'EXPERIMENTAR A VOZ →',finalTitle:'A sua atividade pode tornar-se a próxima presença real do território.',finalLead:'Sarlat é a zona piloto. À medida que chegam profissionais reais, as suas vitrines substituem os exemplos.',finalBtn:'OCUPAR O MEU LUGAR NO VALE · 45 € / MÊS →',note:'DIGIY VALE DA DORDOGNE · Sarlat zona piloto · Périgord · rio Dordogne · ouro DIGIYLYFE.',back:'← DIGIYLYFE FRANÇA'},
it:{pilot:'Sarlat · zona pilota',ey:'PÉRIGORD NOIR · VALLE DELLA DORDOGNA · TERRITORIO STAGIONALE',hero:'I professionisti reali vengono prima. Sarlat è la zona pilota; i posti disponibili proiettano tutta la Valle della Dordogna.',hot:'⚡ ANNUNCI / BISOGNI DEL MOMENTO →',real:'VEDI I PROFESSIONISTI REALI →',join:'SONO UN PROFESSIONISTA NELLA VALLE →',price:'Identità locale · contatto diretto · 0 % commissioni',realTitle:'Già aperti · Sarlat zona pilota',realLead:'Queste sono presenze DIGIYLYFE reali con sede a Sarlat. Appaiono sempre prima degli esempi.',open:'APRI LA PRESENZA →',needTitle:'Cosa cerchi?',needLead:'ANNUNCI viene prima, seguito dai bisogni umani del territorio. LA VOCE resta un motore di ricerca.',placesTitle:'Posti disponibili nella Valle',placesLead:'Il vuoto non viene mostrato. Viene proiettato. Gli esempi rappresentano posti aperti nella Valle della Dordogna senza inventare falsi membri.',badge:'ESEMPIO · POSTO DISPONIBILE',demo:'APRI IL MODELLO →',voice:'PROVA LA VOCE →',finalTitle:'La tua attività può diventare la prossima presenza reale del territorio.',finalLead:'Sarlat è la zona pilota. Quando arrivano professionisti reali, le loro vetrine prendono il posto degli esempi.',finalBtn:'PRENDI IL MIO POSTO NELLA VALLE · 45 € / MESE →',note:'DIGIY VALLE DELLA DORDOGNA · Sarlat zona pilota · Périgord · fiume Dordogna · oro DIGIYLYFE.',back:'← DIGIYLYFE FRANCIA'},
de:{pilot:'Sarlat · Pilotgebiet',ey:'PÉRIGORD NOIR · DORDOGNE-TAL · SAISONALES GEBIET',hero:'Echte Profis stehen zuerst. Sarlat ist das Pilotgebiet; freie Plätze zeigen das gesamte Dordogne-Tal.',hot:'⚡ ANZEIGEN / AKTUELLE BEDÜRFNISSE →',real:'ECHTE PROFIS ANZEIGEN →',join:'ICH BIN PROFI IM DORDOGNE-TAL →',price:'Lokale Identität · direkter Kontakt · 0 % Provision',realTitle:'Bereits geöffnet · Pilotgebiet Sarlat',realLead:'Dies sind echte DIGIYLYFE-Präsenzen mit Sitz in Sarlat. Sie stehen immer vor den Beispielen.',open:'PRÄSENZ ÖFFNEN →',needTitle:'Was suchen Sie?',needLead:'ANZEIGEN steht zuerst, gefolgt von den menschlichen Bedürfnissen des Gebiets. DIE STIMME bleibt eine Suche.',placesTitle:'Freie Plätze im Dordogne-Tal',placesLead:'Leere Flächen werden nicht gezeigt, sondern projiziert. Beispiele zeigen offene Plätze im Dordogne-Tal ohne erfundene Mitglieder.',badge:'BEISPIEL · FREIER PLATZ',demo:'MODELL ÖFFNEN →',voice:'SPRACHSUCHE TESTEN →',finalTitle:'Ihre Tätigkeit kann die nächste echte Präsenz im Gebiet werden.',finalLead:'Sarlat ist das Pilotgebiet. Sobald echte Profis hinzukommen, ersetzen ihre Auftritte die Beispiele.',finalBtn:'MEINEN PLATZ IM TAL NEHMEN · 45 € / MONAT →',note:'DIGIY DORDOGNE-TAL · Sarlat Pilotgebiet · Périgord · Dordogne · DIGIYLYFE-Gold.',back:'← DIGIYLYFE FRANKREICH'},
nl:{pilot:'Sarlat · pilotgebied',ey:'PÉRIGORD NOIR · DORDOGNEVALLEI · SEIZOENSGEBIED',hero:'Echte professionals staan vooraan. Sarlat is het pilotgebied; beschikbare plekken projecteren de hele Dordognevallei.',hot:'⚡ ADVERTENTIES / ACTUELE BEHOEFTEN →',real:'BEKIJK ECHTE PROFESSIONALS →',join:'IK BEN PROFESSIONAL IN DE VALLEI →',price:'Lokale identiteit · direct contact · 0 % commissie',realTitle:'Al geopend · Sarlat pilotgebied',realLead:'Dit zijn echte DIGIYLYFE-aanwezigheden in Sarlat. Ze verschijnen altijd vóór de voorbeelden.',open:'OPEN AANWEZIGHEID →',needTitle:'Wat zoekt u?',needLead:'ADVERTENTIES komt eerst, gevolgd door menselijke behoeften in het gebied. DE STEM blijft een zoekmachine.',placesTitle:'Beschikbare plekken in de vallei',placesLead:'Leegte wordt niet getoond maar geprojecteerd. Voorbeelden tonen open plekken in de Dordognevallei zonder fictieve leden.',badge:'VOORBEELD · PLEK BESCHIKBAAR',demo:'OPEN MODEL →',voice:'PROBEER STEMZOEKEN →',finalTitle:'Uw activiteit kan de volgende echte aanwezigheid in het gebied worden.',finalLead:'Sarlat is het pilotgebied. Zodra echte professionals aansluiten, nemen hun vitrines de plaats van voorbeelden in.',finalBtn:'NEEM MIJN PLEK IN DE VALLEI · 45 € / MAAND →',note:'DIGIY DORDOGNEVALLEI · Sarlat pilotgebied · Périgord · Dordogne · DIGIYLYFE-goud.',back:'← DIGIYLYFE FRANKRIJK'},
ar:{pilot:'سارلا · منطقة تجريبية',ey:'بيريغور نوار · وادي دوردوني · منطقة موسمية',hero:'يظهر المهنيون الحقيقيون أولاً. سارلا هي المنطقة التجريبية، والأماكن المتاحة تمثل كامل وادي دوردوني.',hot:'⚡ الإعلانات / الاحتياجات الحالية ←',real:'عرض المهنيين الحقيقيين ←',join:'أنا مهني في الوادي ←',price:'هوية محلية · تواصل مباشر · 0٪ عمولة',realTitle:'مفتوح فعلاً · سارلا منطقة تجريبية',realLead:'هذه حضورات DIGIYLYFE حقيقية مقرها سارلا، وتظهر دائماً قبل الأمثلة.',open:'فتح الحضور ←',needTitle:'ما الذي تبحث عنه؟',needLead:'الإعلانات أولاً، ثم الاحتياجات البشرية للمنطقة. الصوت يبقى أداة بحث.',placesTitle:'أماكن متاحة في الوادي',placesLead:'لا نعرض الفراغ بل نقدمه كنموذج. الأمثلة تمثل أماكن مفتوحة في وادي دوردوني دون اختلاق أعضاء وهميين.',badge:'مثال · مكان متاح',demo:'فتح النموذج ←',voice:'جرّب البحث بالصوت ←',finalTitle:'يمكن لنشاطك أن يصبح الحضور الحقيقي التالي في المنطقة.',finalLead:'سارلا هي المنطقة التجريبية. ومع وصول مهنيين حقيقيين، تحل واجهاتهم محل الأمثلة.',finalBtn:'احجز مكاني في الوادي · 45 € / شهر ←',note:'DIGIY وادي دوردوني · سارلا منطقة تجريبية · بيريغور · نهر دوردوني · ذهب DIGIYLYFE.',back:'← DIGIYLYFE فرنسا'}
}'''
s = s[:copy_pos] + copy + s[state_pos:]

labels = r'''var LABELS={
fr:{announcements:'ANNONCES',transport:'SE DÉPLACER',artisan:'TROUVER UN ARTISAN',accommodation:'DORMIR OU LOUER',food:'MANGER OU RÉSERVER',shopping:'ACHETER LOCAL',beauty:'BEAUTÉ & BIEN-ÊTRE',jobs:'EMPLOI ET MISSIONS',guidance:'LA VOIX'},
en:{announcements:'LISTINGS',transport:'GET AROUND',artisan:'FIND A TRADESPERSON',accommodation:'STAY OR RENT',food:'EAT OR BOOK',shopping:'SHOP LOCAL',beauty:'BEAUTY & WELLNESS',jobs:'JOBS & GIGS',guidance:'THE VOICE'},
es:{announcements:'ANUNCIOS',transport:'DESPLAZARSE',artisan:'ENCONTRAR UN ARTESANO',accommodation:'ALOJARSE O ALQUILAR',food:'COMER O RESERVAR',shopping:'COMPRAR LOCAL',beauty:'BELLEZA Y BIENESTAR',jobs:'EMPLEO Y MISIONES',guidance:'LA VOZ'},
pt:{announcements:'ANÚNCIOS',transport:'DESLOCAR-SE',artisan:'ENCONTRAR UM ARTESÃO',accommodation:'DORMIR OU ALUGAR',food:'COMER OU RESERVAR',shopping:'COMPRAR LOCAL',beauty:'BELEZA E BEM-ESTAR',jobs:'EMPREGO E MISSÕES',guidance:'A VOZ'},
it:{announcements:'ANNUNCI',transport:'SPOSTARSI',artisan:'TROVARE UN ARTIGIANO',accommodation:'DORMIRE O AFFITTARE',food:'MANGIARE O PRENOTARE',shopping:'COMPRARE LOCALE',beauty:'BELLEZZA E BENESSERE',jobs:'LAVORO E INCARICHI',guidance:'LA VOCE'},
de:{announcements:'ANZEIGEN',transport:'UNTERWEGS SEIN',artisan:'HANDWERKER FINDEN',accommodation:'ÜBERNACHTEN ODER MIETEN',food:'ESSEN ODER RESERVIEREN',shopping:'LOKAL EINKAUFEN',beauty:'SCHÖNHEIT & WELLNESS',jobs:'JOBS UND AUFTRÄGE',guidance:'DIE STIMME'},
nl:{announcements:'ADVERTENTIES',transport:'VERPLAATSEN',artisan:'EEN VAKMAN VINDEN',accommodation:'OVERNACHTEN OF HUREN',food:'ETEN OF RESERVEREN',shopping:'LOKAAL KOPEN',beauty:'SCHOONHEID & WELZIJN',jobs:'WERK EN OPDRACHTEN',guidance:'DE STEM'},
ar:{announcements:'إعلانات',transport:'التنقل',artisan:'العثور على حرفي',accommodation:'الإقامة أو الاستئجار',food:'الأكل أو الحجز',shopping:'الشراء محلياً',beauty:'الجمال والعافية',jobs:'وظائف ومهام',guidance:'الصوت'}
};'''
needle = ";var state={need:''}"
if needle not in s:
    raise SystemExit('state insertion guard failed')
s = s.replace(needle, ';' + labels + "var state={need:''}", 1)

old_render = "b.innerHTML='<strong>'+n[1]+'</strong><span>'+n[2]+'</span>'"
new_render = "b.innerHTML='<strong>'+n[1]+'</strong><span>'+((LABELS[lang()]||LABELS.fr)[n[0]]||n[2])+'</span>'"
if s.count(old_render) != 1:
    raise SystemExit('renderNeeds guard failed')
s = s.replace(old_render, new_render, 1)

old_copy_loop = "[['ey','ey'],['heroLead','hero'],['hotAnnouncements','hot'],['realBtn','real'],['joinBtn','join'],['priceLead','price']"
new_copy_loop = "[['pilotLabel','pilot'],['ey','ey'],['heroLead','hero'],['hotAnnouncements','hot'],['realBtn','real'],['joinBtn','join'],['priceLead','price']"
if s.count(old_copy_loop) != 1:
    raise SystemExit('copy loop guard failed')
s = s.replace(old_copy_loop, new_copy_loop, 1)

if '<link rel="manifest" href="/manifest.json?v=20260824-tarif-unique">' not in s:
    raise SystemExit('PWA manifest guard failed')
if s.count('EXEMPLE · PLACE À PRENDRE') < 1:
    raise SystemExit('projection badge guard failed')
if "var NEEDS=[['announcements'" not in s:
    raise SystemExit('announcements order guard failed')

p.write_text(s, encoding='utf-8')
print('Dordogne direct page aligned with MASTER')
